### ISSUE TITLE
segfault with underscore in var name

### ISSUE THREAD

**Issue by mcswell** [mhulden/foma#77]
I get a seg fault with the following xfst code:
    def X A_B ;
Similarly:
    regex A_B ;
I guess the ASCII underscore isn't allowed in variable names (is there a place where a valid var name is defined? Foma seems slightly more liberal than xfst, where IIRC digits are not allowed in names).  But even if underscores are not allowed, it should probably not segfault...

**Comment by AmbientLighter** [comment]
@mhulden I think this issue is fixed now, let's close it.

**Comment by mcswell** [comment]
@AmbientLighter: What version is this fixed in?  I'm using 0.9.18alpha, which is the newest version offered by Ubuntu, and also the version listed at the bottom of https://github.com/mhulden/foma/tree/master/foma.  I still get the segfault.  Perhaps the merged version needs to be pushed somewhere?

**Comment by AmbientLighter** [comment]
Fix has been submitted here 
https://github.com/mhulden/foma/commit/ae32fa7fae2844565d4c18242e04c0bd9e29da51

As I understand, there is no release with this or any other fixes applied. It means that you may build foma from source code yourself. 

It would be best to setup gitlab ci pipeline so that binaries would be built automatically. I can do it myself, but I am not really sure would it be merged by @mhulden because project looks unmaintained.

**Comment by mhulden** [comment]
Yes, there's been no official releases since 0.9.18alpha, but pull requests are handled and the underscore fix is in the source.

I'd be happy to merge a gitlab ci pipeline.

**Comment by AmbientLighter** [comment]
@mhulden Please see related merge request https://github.com/mhulden/foma/pull/101

**Comment by AmbientLighter** [comment]
@mcswell Fresh binaries are available here: https://github.com/AmbientLighter/foma/actions/runs/824350546
